# Generated by Django 4.2.11 on 2025-12-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_game_rating_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_text',
            field=models.TextField(),
        ),
    ]
