# Generated by Django 4.2.11 on 2025-12-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_rating_rating_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
