# Generated by Django 4.2.11 on 2025-12-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rating_dislikes_rating_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='votes',
        ),
    ]
