# Generated by Django 4.2.11 on 2025-12-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_rating_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.URLField(blank=True, help_text='URL to game cover image', max_length=500),
        ),
    ]
