# Generated by Django 4.2.11 on 2025-12-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_game_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video_description',
            field=models.TextField(blank=True, help_text='Short description of the video'),
        ),
        migrations.AddField(
            model_name='game',
            name='youtube_video',
            field=models.URLField(blank=True, help_text='YouTube video URL', max_length=500),
        ),
    ]
